name: Build release zip

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build release zip
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup WP-CLI
        uses: godaddy-wordpress/setup-wp-cli@1

      - name: Run package installs and builds
        run: |
          composer install
          composer update
          npm i
          npm run build
          cd css/
          /usr/bin/php style.php 5 > style.css
          cd ..

      - name: Run WordPress Coding Standard fixes
        run: vendor/bin/phpcbf --extensions=php --ignore=*/attributes/*,*/example/*,*/css/*,*/vendor/*,*/node_modules/*,*/svn/* --standard=ruleset.xml .

      - name: Run WordPress Coding Standard checks
        run: vendor/bin/phpcs --extensions=php --ignore=*/attributes/*,*/example/*,*/css/*,*/vendor/*,*/node_modules/*,*/svn/* --standard=ruleset.xml .

      - name: Set version number 1
        uses: richardrigutins/replace-in-files@v2
        with:
          files: 'nested-ordered-lists-for-block-editor.php'
          search-text: '@@VersionNumber@@'
          replacement-text: ${{ github.ref_name }}

      - name: Set version number 2
        uses: richardrigutins/replace-in-files@v2
        with:
          files: 'readme.txt'
          search-text: '@@VersionNumber@@'
          replacement-text: ${{ github.ref_name }}

      - name: Create ZIP release
        run: |
          rm -fr .git
          rm -fr assets
          rm -fr build
          rm -fr releases
          rm -fr svn
          rm -fr languages
          rm -fr example
          rm -fr src
          rm changelog.md
          rm readme.md
          rm ruleset.xml
          cd ..
          mv ${{ github.event.repository.name }} nested-ordered-lists-for-block-editor
          zip -r -q nested-ordered-lists-for-block-editor_${{ github.ref_name }}.zip nested-ordered-lists-for-block-editor/* -x "*/.git/*" "*/.github/*" "*/blocks/*/src/*" "*/docs/*" "*/phpcs.xml" "*/composer.json" "*/composer.lock" "*/package.json" "*/package-lock.json" "*/ruleset.xml" "*/.gitignore" "*/vendor/*" "*/node_modules/*" "/.editorconfig"
          mv nested-ordered-lists-for-block-editor ${{ github.event.repository.name }}
          cp nested-ordered-lists-for-block-editor_${{ github.ref_name }}.zip ${{ github.event.repository.name }}/

      - name: Unzip release ZIP
        run: unzip nested-ordered-lists-for-block-editor_${{ github.ref_name }}.zip

      - name: Run Plugin Check
        uses: wordpress/plugin-check-action@v1
        with:
            build-dir: './nested-ordered-lists-for-block-editor/'

      - name: Create Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: nested-ordered-lists-for-block-editor_${{ github.ref_name }}.zip
